name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --immutable --ignore-optional
      - run: yarn run build
      - run: yarn run deploy ${{ secrets.CRYSTAL_ID }} ${{ secrets.CRYSTAL_TOKEN }}  ${{ secrets.POTATO_ID }} ${{ secrets.POTATO_TOKEN }} ${{ secrets.SWEAR_ID }} ${{ secrets.SWEAR_TOKEN }} ${{ secrets.YEET_ID }} ${{ secrets.YEET_TOKEN }}
